spring_profiles: mysql

database:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mysql://${DB_ADDR}:${DB_PORT}/${DB_ENV_DB:uaa}
  username: ${DB_ENV_USER:user}
  password: ${DB_ENV_PASS:pass}

scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - admin@sequenceiq.com|seqadmin|admin@sequenceiq.com|Default|User|openid,cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,sequenceiq.cloudbreak.admin,sequenceiq.cloudbreak.user,sequenceiq.account.abcd1234.SequenceIQ,periscope.cluster,cloudbreak.events,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,cloudbreak.recipes
